app/models.py
# -*- coding: utf-8 -*-

"""
    DODOA
        A better OA system for Design Management.
    
    :Author:    Bruce Frank Wang <bruce.frank.wang@gmail.com>
    :Time:      2019-02-20 02:15
    :copyright: © 2019 Bruce Frank Wang <bruce.frank.wang@gmail.com>
    :license:   GPL v3, see LICENSE for more details.
"""

from app import db


class Gender(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False, unique=True)
    name_zh = db.Column(db.String, nullable=False, unique=True)
    employee_list = db.relationship('Employee',
                                    backref=db.backref('gender', lazy='joined'),
                                    lazy='dynamic'
                                    )

    def __repr__(self):
        return "<Gender (name='{name}')>".format(name=self.name)


class Specialty(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False, unique=True)
    employee_list = db.relationship('Employee',
                                    backref=db.backref('specialty', lazy='joined'),
                                    lazy='dynamic'
                                    )

    def __repr__(self):
        return "<Specialty (name='{name}')>".format(name=self.name)


class Employee(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    birthday = db.Column(db.Date)
    accession_day = db.Column(db.Date)
    gender_id = db.Column(db.Integer, db.ForeignKey('gender.id'), nullable=False)
    specialty_id = db.Column(db.Integer, db.ForeignKey('specialty.id'), nullable=False)

    def __repr__(self):
        return "<Employee (name='{name}')>".format(name=self.name)


class Project(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False, unique=True)
    code = db.Column(db.String)
    location = db.Column(db.String)

    def __repr__(self):
        return "<Project (name='{name}')>".format(name=self.name)


class LandBlock(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String)

    def __repr__(self):
        return "<LandBlock (name='{name}')>".format(name=self.name)


class DesignStandard(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    code = db.Column(db.String, nullable=False)

    def __repr__(self):
        return "<DesignStandard (name='{name}')>".format(name=self.name)

app/__init__.py
# -*- coding: utf-8 -*-

"""
    DODOA
        A better OA system for Design Management.
    
    :Author:    Bruce Frank Wang <bruce.frank.wang@gmail.com>
    :Time:      2019-02-19 22:09
    :copyright: © 2019 Bruce Frank Wang <bruce.frank.wang@gmail.com>
    :license:   GPL v3, see LICENSE for more details.
"""

import os

import click
from flask import Flask

from app.config import config
from app.extensions import db, moment, migrate
from app.models import Gender, Employee, Project
from app.views import bp as bp_main


def create_app(config_name=None):
    """
    Create the Flask app via Factory pattern.
    :param config_name:
    :return: the Flask app object.
    """
    if config_name is None:
        config_name = os.getenv('FLASK_ENV', 'development')

    app = Flask(__name__)
    app.config.from_object(config[config_name])

    # register_logging(app)
    register_extensions(app)
    register_blueprints(app)
    # register_errors(app)
    register_commands(app)
    # register_shell_context(app)
    # register_template_context(app)
    # register_request_handlers(app)
    return app


def register_extensions(app):
    db.init_app(app)
    migrate.init_app(app)
    moment.init_app(app)


def register_blueprints(app):
    app.register_blueprint(bp_main)


def register_commands(app):
    @app.cli.command('init')
    @click.option('--drop', is_flag=True, help='Create after drop.')
    def db_init(drop):
        """
        Initialize the database of the Flask application.
        Create the tables, and fill some basic data.
        :return: None.
        """
        if drop:
            click.confirm('This operation will delete the database, do you want to continue?', abort=True)
            click.echo('Dropping tables...')
            db.drop_all()
            click.echo('Dropped.')

        click.echo('Creating database...')
        db.create_all()
        click.echo('Created.')

        click.echo('Filling basic data...')
        # Data for class Gender().
        db.session.add_all([
            Gender(name='Unknown', name_zh='未知'),
            Gender(name='Male', name_zh='男性'),
            Gender(name='Female', name_zh='女性'),
        ])

        # Data for class Company().
        db.session.add_all([
            Project(name='南京2016G61地块项目', code='海珀'),
            Project(name='南京2017G41地块项目', code='海悦'),
        ])

        click.echo('Filled.')

        click.echo('Committing...')
        db.session.commit()
        click.echo('Commit succeed.')

app/views.py
# -*- coding: utf-8 -*-

"""
    DODOA
        A better OA system for Design Management.
    
    :Author:    Bruce Frank Wang
    :File Time: 2019-02-20 13:01
    :copyright: © 2019 Bruce Frank Wang <bruce.frank.wang@gmail.com>
    :license:   GPL v3, see LICENSE for more details.
"""

from flask import Blueprint, render_template

from app.models import Project


bp = Blueprint('main', __name__)


@bp.route('/')
@bp.route('/index')
def index():
    return render_template('index.html')


@bp.route('/login')
def login():
    return render_template('login.html')


@bp.route('/project')
def project_brief():
    project_list = Project.query.all()
    return render_template('project_brief.html', project_list=project_list)


@bp.route('/project/<name>')
def project(name):
    p = Project.query.filter_by(name=name).first_or_404()
    return render_template('project.html', project=p)


@bp.route('/plan')
def plan():
    return render_template('plan.html')


@bp.route('/resource')
def resource():
    return render_template('resource.html')


@bp.route('/employee')
def employee():
    return render_template('employee.html')

app/templates/_navigator.html
<!--
    DODOA
        A better OA system for Design Management.
    
    :Author:    Bruce Frank Wang
    :File Time: 2019-02-20 16:55
    :copyright: © 2019 Bruce Frank Wang <bruce.frank.wang@gmail.com>
    :license:   GPL v3, see LICENSE for more details.
-->

<!-- TODO: Add pop menu -->
{% macro navigator() %}
<div class="navigator">
    <span><a href="{{ url_for('main.index') }}">DODOA</a></span>
    <span><a href="{{ url_for('main.project_brief') }}">Project</a></span>
    {% if project_menu_list %}
        <ul class="menu">
            {% for item in project_menu_list %}
            <li class="menu_item" onmouseover="displaySubMenu(this)" onmouseout="hideSubMenu(this)">
                <a href="{{ url_for(item.url) }}">item.text</a>
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    <span><a href="{{ url_for('main.plan') }}">Plan</a></span>
    <span><a href="{{ url_for('main.employee') }}">Employee</a></span>
    <span><a href="{{ url_for('main.resource') }}">Resource</a></span>
</div>
{% endmacro %}

app/templates/_page_foot.html
<!--
    DODOA
        A better OA system for Design Management.
    
    :Author:    Bruce Frank Wang
    :File Time: 2019-02-20 16:55
    :copyright: © 2019 Bruce Frank Wang <bruce.frank.wang@gmail.com>
    :license:   GPL v3, see LICENSE for more details.
-->

{% macro page_foot() %}
<div class="container_page_foot">
    Supported by DODOA
</div>
{% endmacro %}

app/templates/base.html
<!--
    DODOA
        A better OA system for Design Management.
    
    :Author:    Bruce Frank Wang
    :File Time: 2019-02-20 16:50
    :copyright: © 2019 Bruce Frank Wang <bruce.frank.wang@gmail.com>
    :license:   GPL v3, see LICENSE for more details.
-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>{{ title }} - DODOA</title>
    {% else %}
        <title>Frontpage - DODOA</title>
    {% endif %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/common.css') }}">

    <script type="text/javascript">
        function displaySubMenu(li) {
            var subMenu = li.getElementsByTagName("ul")[0];
            subMenu.style.display = "block";
        }

        function hideSubMenu(li) {
            var subMenu = li.getElementsByTagName("ul")[0];
            subMenu.style.display = "none";
        }
    </script>

</head>
<body>
{% block navigator %}
{% endblock %}

<hr>

{% block content %}
{% endblock %}

<hr>

{% block page_foot %}
{% endblock %}
</body>
</html>

app/templates/index.html
<!--
    DODOA
        A better OA system for Design Management.
    
    :Author:    Bruce Frank Wang
    :File Time: 2019-02-20 15:46
    :copyright: © 2019 Bruce Frank Wang <bruce.frank.wang@gmail.com>
    :license:   GPL v3, see LICENSE for more details.
-->

{% extends 'base.html' %}

{% from "_navigator.html" import navigator %}
{% from "_page_foot.html" import page_foot %}

{% block navigator %}
    {{ navigator() }}
{% endblock %}

{% block content %}
    {{ navigator() }}
{% endblock %}

{% block page_foot %}
    {{ page_foot() }}
{% endblock %}

app/templates/project.html
<!--
    DODOA
        A better OA system for Design Management.
    
    :Author:    Bruce Frank Wang
    :File Time: 2019-02-20 17:30
    :copyright: © 2019 Bruce Frank Wang <bruce.frank.wang@gmail.com>
    :license:   GPL v3, see LICENSE for more details.
-->

{% extends 'base.html' %}

{% from "_navigator.html" import navigator %}
{% from "_page_foot.html" import page_foot %}

{% block navigator %}
    {{ navigator() }}
{% endblock %}

{% block content %}
    <h1>Project: {{ project.name }}</h1>
        more details...
{% endblock %}

{% block page_foot %}
    {{ page_foot() }}
{% endblock %}

app/templates/project_brief.html
<!--
    DODOA
        A better OA system for Design Management.
    
    :Author:    Bruce Frank Wang
    :File Time: 2019-02-20 20:53
    :copyright: © 2019 Bruce Frank Wang <bruce.frank.wang@gmail.com>
    :license:   GPL v3, see LICENSE for more details.
-->

{% extends 'base.html' %}

{% from "_navigator.html" import navigator %}
{% from "_page_foot.html" import page_foot %}

{% block navigator %}
    {{ navigator() }}
{% endblock %}

{% block content %}
    {% if project_list %}
        {% for project in project_list %}
            <div>
                <a href="{{ url_for('main.project', name=project.name) }}">{{ project.name }}</a>
            </div>
        {% endfor %}
    {% else %}
        <h1>No project jet.</h1>
    {% endif %}
{% endblock %}

{% block page_foot %}
    {{ page_foot() }}
{% endblock %}